### PR TITLE
RF | POM - EntityArithmeticFunction

### PR DESCRIPTION
**Pull request by Wis13**
Create ArithmeticFunctionPage
Create ArithmeticFunctionEditPage
Modify MainPage
[Trello](https://trello.com/c/IXxn4TIx/994-rf-pom-entityboarddraftrecordtest-testcreatedraftrecord)

### CODE REVIEW

**Review by MariaMoroz — COMMENTED** [review]
А где тесты?

**Comment by MichaelMicrof** [comment]
In the Trello card, please, add link on this PR

**Review by MichaelMicrof — APPROVED** [review]
In the Trello card, please, add link on this PR

**Review by SergeiKuznetsov — APPROVED** [review]

**Comment by Wis13** [comment]
POM Create ArithmeticFunctionPage

**Pull request merged**
