### PR TITLE
Enable testRichardGobal

### PR DESCRIPTION
**Pull request by RichardGob**

### CODE REVIEW

**Comment by SergeiKuznetsov** [comment]
Failed tests:   
**testLudaPetkel**(GroupBugBustersTest): expected [true] but found [false]
**testRichardGobal**(GroupSquirrelsTest): expected [In Stock] but found []
**testSergeIschenko**(SergeyIschenkoTest): stale element reference: element is not attached to the page document(..)

**Comment by SergeiKuznetsov** [comment]
Failed tests:   **testTwoVkorenevskyy**(KorikUmanTest): expected [Found 10 results] but found []

**Comment by SergeiKuznetsov** [comment]
Failed tests:   **testSergeIschenko**(SergeyIschenkoTest): stale element reference: element is not attached to the page document(..)

**Comment by SergeiKuznetsov** [comment]
Теперь падает только твой тест
Failed tests:   **testRichardGobal**(GroupSquirrelsTest): expected [In Stock] but found []

**Comment by SergeiKuznetsov** [comment]
Failed tests:   **testRichardGobal**(GroupSquirrelsTest): expected [In Stock] but found []
  **UlianaShutaTest**(GroupBooleanAutocratsTest): element not interactable(..)

**Review by SergeiKuznetsov — APPROVED** [review]

**Review by NYerlan — APPROVED** [review]
Looks good!

**Pull request merged**
